language: objective-c
osx_image: xcode11.3
xcode_project: WoopEvents.xcodeproj
xcode_scheme: WoopEvents
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro
before_install:
- brew install carthage && brew install swiftlint
- carthage update --new-resolver --platform ios --cache-builds
- swiftlint
