language: objective-c
osx_image: xcode10.2
xcode_workspace: WoopEvents.xcworkspace
xcode_scheme: WoopEvents
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
before_install:
- brew install carthage
- carthage update --platform ios --cache-builds