name: Swift

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Carthage
      run: carthage update --platform iOS --new-resolver --cache-builds
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
